import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <div>
      <Navbar></Navbar>
     </div>
     <main className=" h-screen  max-h-[500px] flex items-center justify-center min-h-screen">
         {children}
     </main>
     <footer className="mx-auto text-center">
      <h1>footer </h1>
     </footer>
      </body>
    </html>
  );
}
